lints.workspace = true

[package]
name = "pkpass-server"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
pkpass.workspace = true
